In [2]:
# --- NumPy Basic ---

In [3]:
import numpy as np
print("NumPy Version:", np.__version__)

NumPy Version: 2.2.5


In [4]:
# --- 4. NumPy Creating Arrays ---
import numpy as np
arr_0d = np.array(42)
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("2D Array:\n", arr_2d)
print("Dimensions:", arr_2d.ndim)

2D Array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2


In [5]:
# --- 5. NumPy Array Indexing ---
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("1st element on 1st row: ", arr[0, 0])
print("Last element of 2nd row:", arr[1, -1])

1st element on 1st row:  1
Last element of 2nd row: 10


In [6]:
# --- 6. NumPy Array Slicing ---
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("Slice 1 to 5:", arr[1:5])
print("Step slice:", arr[0:7:2])

Slice 1 to 5: [2 3 4 5]
Step slice: [1 3 5 7]


In [7]:
# --- 7. NumPy Data Types ---
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i') # float to int
print("New dtype:", newarr.dtype)

New dtype: int32


In [8]:
# --- 8. NumPy Copy vs View ---
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[0] = 42
print("Copy (x):", x) # No change
print("View (y):", y) # Changes to 42

Copy (x): [1 2 3 4 5]
View (y): [42  2  3  4  5]


In [9]:
# --- 9. NumPy Array Shape ---
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Shape of array:", arr.shape)

Shape of array: (2, 4)


In [10]:
# --- 10. NumPy Array Reshape ---
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print("Reshaped:\n", newarr)
flat_arr = newarr.reshape(-1)
print("Flattened:", flat_arr)

Reshaped:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
# --- 11. NumPy Array Iterating ---
import numpy as np
arr = np.array([[1, 2], [3, 4]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [12]:
# --- 12. NumPy Array Join ---
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_concat = np.concatenate((arr1, arr2))
print("Concatenated:", arr_concat)

Concatenated: [1 2 3 4 5 6]


In [13]:
# --- 13. NumPy Array Split ---
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print("Split part 1:", newarr[0])

Split part 1: [1 2]


In [14]:
# --- 14. NumPy Array Search ---
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print("Indexes of 4:", x)

Indexes of 4: (array([3, 5, 6]),)


In [15]:
# --- 15. NumPy Array Sort ---
import numpy as np
arr = np.array([3, 2, 0, 1])
print("Sorted Array:", np.sort(arr))

Sorted Array: [0 1 2 3]


In [16]:
# --- 16. NumPy Array Filter ---
import numpy as np
arr = np.array([41, 42, 43, 44])
newarr = arr[arr > 42]
print("Filtered Array:", newarr)

Filtered Array: [43 44]
